/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#472a00',
        'inverse-primary': '#005ac2',
        'background': '#13131b',
        'on-secondary-fixed-variant': '#005236',
        'error': '#ffb4ab',
        'surface': '#13131b',
        'primary': '#adc6ff',
        'surface-container-high': '#292932',
        'outline': '#8c909f',
        'surface-variant': '#34343d',
        'on-background': '#e4e1ed',
        'on-primary-fixed': '#001a42',
        'primary-container': '#4d8eff',
        'tertiary-container': '#ca8100',
        'surface-dim': '#13131b',
        'surface-tint': '#adc6ff',
        'on-tertiary-fixed-variant': '#653e00',
        'primary-fixed': '#d8e2ff',
        'secondary-fixed': '#6ffbbe',
        'on-surface-variant': '#c2c6d6',
        'surface-container-highest': '#34343d',
        'on-tertiary-container': '#3e2400',
        'surface-container-low': '#1b1b23',
        'on-primary-container': '#00285d',
        'inverse-surface': '#e4e1ed',
        'secondary-container': '#00a572',
        'tertiary-fixed-dim': '#ffb95f',
        'tertiary': '#ffb95f',
        'on-error-container': '#ffdad6',
        'on-primary-fixed-variant': '#004395',
        'on-tertiary-fixed': '#2a1700',
        'surface-container-lowest': '#0d0d15',
        'on-primary': '#002e6a',
        'surface-container': '#1f1f27',
        'on-surface': '#e4e1ed',
        'inverse-on-surface': '#302f39',
        'error-container': '#93000a',
        'surface-bright': '#393842',
        'on-error': '#690005',
        'outline-variant': '#424754',
        'primary-fixed-dim': '#adc6ff',
        'tertiary-fixed': '#ffddb8',
        'on-secondary': '#003824',
        'secondary-fixed-dim': '#4edea3',
        'on-secondary-container': '#00311f',
        'secondary': '#4edea3',
        'on-secondary-fixed': '#002113',
      },
      fontFamily: {
        headline: ['var(--font-space-grotesk)'],
        body: ['var(--font-inter)'],
        label: ['var(--font-space-grotesk)'],
        mono: ['var(--font-jetbrains-mono)'],
      },
    },
  },
  plugins: [],
};
